name: Daily Commit Workflow

on:
  schedule:
    # Runs every day at 01:15 UTC
    - cron: '15 1 * * *'
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make a commit - 24f2001499@ds.study.iitm.ac.in
        run: |
          echo "Daily update: $(date)" >> daily.txt
          git config user.name "GitHub Action"
          git config user.email "24f2001499@ds.study.iitm.ac.in"
          git add daily.txt
          git commit -m "Daily commit: $(date)" || echo "Nothing to commit"
          git push
