name: Daily Commit 24f2001499@ds.study.iitm.ac.in

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 04:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Update timestamp
        run: date > last-updated.txt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Daily commit by 24f2001409@ds.study.iitm.ac.in"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
